### ISSUE TITLE
项目启动问题

### ISSUE THREAD

**Issue by Sandra310** [searchfe/lavas-demo-blog#1]
我想咨询个问题
1、我浏览器启动github上的demo链接是可以看到service worker信息的
2、代码下载到我本地 run dev 后 localhost:8082后 service worker什么消息都木有
![image](https://user-images.githubusercontent.com/30719502/39528380-85ed9fae-4e56-11e8-9b93-37a8ec258209.png)

localhost按说是可以使用Service Worker的，lavas官网的安装启动步骤也试过，仍然是一样的结果，想问问到底是什么原因呢？

**Comment by PengXing** [comment]
只有编译之后才会生成 service worker 文件，开发模式下不会

因为开发模式下开启 service worker，会干扰调试和开发工作
